#!/bin/bash -l

#
# Things to check before file ready to submit
#
# When filling out this script start at the BOTTOM and finish at the TOP. 
#
# GRAPH_NAME is the correct name. 
# The job name matches the type and graph e.g. base_attack_IEEE_300 or base_strain_IEEE_14
# Number of tasks in the array matches the number of rows inthe HPC_start_up_file
# Time is correct for graph size

# R Version 3.6.1

# The number of array tasks. In the base attack scripts this will be 1-288 in the base strain script this will be 1-3456
# If the missing elements are being filled in this will be customised and need to be updated on the HPC
#
#$ -t 1-9

# 2. Request 1 gigabyte of RAM. Change this to suit your requirements.
#$ -l mem=5G

#This is the name of the graph that is going to be tested.
#It is exported as a global variable so that R can import it to the HPC script
export GRAPH_NAME=${1}
# 5. Your work *must* be done in $TMPDIR 
cd $TMPDIR

# 6. Run your R program.
module unload compilers
module unload mpi
module load r/recommended

Rscript --vanilla /home/ucabbou/Spring_Embeddings_Paper/HPC_files/HPC_files_concentrator/HPC_strain_concentrator_script_r_c.R > HPC_strain_concentrator_script_r_c.R.out

#The $1 is the name of the graph that is going to be tested. this means all graphs are kept seperate and reduces confusion

#There is only 1 file produces every 30 minutes or so there is no point in tarring them up
#The folder will contain the .o files the .e files as well as the .R.out files and the .rds files. These files are easily seperable and the whole folder can be tarred up
#cp -r $TMPDIR/embeddings/* $HOME/Scratch/strainrc/$1/
tar zcvf $HOME/Scratch/strainrc/$1/strain_$JOB_ID.$SGE_TASK_ID.tgz $TMPDIR/embeddings/*

#The R output is moved not tarred as it is small and there is only 1 of it. It contains the job runtime so is useful for analysis
cp $TMPDIR/HPC_strain_concentrator_script_r_c.R.out $HOME/Scratch/strainrc/$1/HPC_strain_concentrator_script_r_c.R.out_$JOB_ID.$SGE_TASK_ID

# Make sure you have given enough time for the copy to complete!
