---
title: "Untitled"
author: "Jonathan Bourne"
date: "10 October 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

#Power flow in c++

This script experiments with using c++ as the calculator for the powerflow


```{r}
packages <- c("RcppArmadillo", "inline", "microbenchmark", "drat")
#file.path("/media/jonno/Seagate Expansion Drive/Msc-Thesis-Data/Cormats")

new.packages <- packages[!(packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)

sapply(packages, library, character.only = TRUE)
rm(list=c("packages",  "new.packages"))

if (!requireNamespace("drat", quietly = TRUE)) install.packages("drat")
drat::addRepo("daqana")
install.packages("RcppArrayFire", configure.args = "--with-arrayfire=/opt/arrayfire")

library(RcppArrayFire)

```



```{r}
flowCalc <- function(A,C){
  B <- t(A) %*% C %*% A
  Imp <- solve(B)
  PTDF <- C %*% A %*% Imp
  Out <- list(Imp = Imp, PTDF= PTDF)
  return(Out)

}

# Create Armadillo function
Rcpp::cppFunction(depends = "RcppArmadillo", code = '
Rcpp::List flowCalcCpp(const arma::mat &Am, const arma::mat &Cm) {
   arma::mat B = inv(trans(Am) * Cm * Am);
   arma::mat PTDF = Cm * Am * B;
   return Rcpp::List::create( Rcpp::Named("Imp") = B ,
                           Rcpp::Named("PTDF") = PTDF );
}')

# Create ArrayFire function
Rcpp::cppFunction(depends = "RcppArrayFire", code = '
Rcpp::List flowCalcAF(const RcppArrayFire::typed_array<f32> &A, 
                      const RcppArrayFire::typed_array<f32> &C) {
  af::array B = af::inverse(af::matmul(af::matmulTN(A, C), A));
  af::array PTDF = af::matmul(af::matmul(C, A), B);
  return Rcpp::List::create( Rcpp::Named("Imp") = B ,
                             Rcpp::Named("PTDF") = PTDF );
}')



library(igraph)
#Create a function to generate dummy data
MakeData <- function(n, edgep){#make an erdos renyi graph of size x
  g <- erdos.renyi.game(n, edgep)
  #convert to adjacency matrix
  Adjmat <- as_adjacency_matrix(g, sparse = F)
  #create random graph and mask the elements with not edge
  Cmat <- matrix(rnorm(n*n), ncol = n)*Adjmat
  ##Output a list of the two matrices
  list(A = Adjmat, C = Cmat)
}

#generate dummy data
set.seed(133)
Data10 <- MakeData(10, 1/1)
Data100 <- MakeData(100, 1/10)
Data1000 <- MakeData(1000, 1/100)

#Compare results
BencdataUpgrade <-microbenchmark::microbenchmark(
  R10 = flowCalc(Data10$A, Data10$C),
  R100 = flowCalc(Data100$A, Data100$C),
  R1000 = flowCalc(Data1000$A, Data1000$C),
  Cpp10 = flowCalcCpp(Data10$A, Data10$C),
  Cpp100 = flowCalcCpp(Data100$A, Data100$C),
  Cpp1000 = flowCalcCpp(Data1000$A, Data1000$C),
  AF10 = flowCalcAF(Data10$A, Data10$C),
  AF100 = flowCalcAF(Data100$A, Data100$C),
  AF1000 = flowCalcAF(Data1000$A, Data1000$C))
```


```{r}


g <- cxxfunction ( signature ( vs = "numeric" ) ,
                   plugin = "RcppArmadillo" , body ='
                   arma :: vec v = Rcpp :: as < arma :: vec >( vs ) ;
                   arma :: mat op = v * v . t () ;
                   double ip = arma :: as_scalar ( v . t () * v ) ;
                   return Rcpp :: List :: create ( Rcpp :: Named ("outer") = op ,
                                                   Rcpp :: Named ("inner") = ip ) ; ')
g2 <- function(x){
  
  ttx <- t(t(x))
  tx <- (t(x))
  
  Out <- list(ttx %*% tx, tx %*% ttx)
  names(Out) <- c("outer", "inner")
  Out
  
}

x <- 7:11
g(x)
g2(x)

microbenchmark(g(x), g2(x), times = 10000)

```



```{r}

lines = '// copy the data to armadillo structures
arma::colvec x = Rcpp::as<arma::colvec> (x_);
arma::mat Y = Rcpp::as<arma::mat>(Y_) ;
arma::colvec z = Rcpp::as<arma::colvec>(z_) ;
// calculate the result
double result = arma::as_scalar(
arma::trans(x) * arma::inv(Y) * z
);
// return it to R
return Rcpp::wrap( result );'

fx <- cxxfunction(signature(x_="numeric",
                            Y_="matrix",
                            z_="numeric" ),
                  body = lines,
                  plugin="RcppArmadillo" )


fx(1:4, diag(4), 1:4)

```

```{r}
library(igraph); library(RcppArmadillo);library(microbenchmark)

#Create the basic R implementation of the equation
flowCalc <- function(A,C){

  B <- t(A) %*% C %*% A
  Imp <- solve(B)
  PTDF <- C %*% A %*% Imp
  Out <- list(Imp = Imp, PTDF= PTDF)
  return(Out)
   
}

flowCalc2 <- function(A,C){

  B <- crossprod(A, C) %*% A
  Imp <- solve(B)
  PTDF <- C %*% A %*% Imp
  Out <- list(Imp = Imp, PTDF= PTDF)
  return(Out)
   
}

#Create the c++ implementation
Rcpp::cppFunction(depends = "RcppArmadillo", code = '
Rcpp::List flowCalcCpp(const arma::mat &Am, const arma::mat &Cm) {
   arma::mat B = inv(trans(Am) * Cm * Am);
   arma::mat PTDF = Cm * Am * B;
   return Rcpp::List::create( Rcpp::Named("Imp") = B ,
                           Rcpp::Named("PTDF") = PTDF );
}')


#Create a function to generate dummy data
MakeData <- function(n, edgep){#make an erdos renyi graph of size x
g <- erdos.renyi.game(n, edgep)
#convert to adjacency matrix
Adjmat <- as_adjacency_matrix(g, sparse = F)
#create random graph and mask the elements with not edge
Cmat <- matrix(rnorm(n*n), ncol = n)*Adjmat
##Output a list of the two matrices
list(A = Adjmat, C = Cmat)
}

#generate dummy data
set.seed(133)
Data10 <- MakeData(10, 1/1)
Data100 <- MakeData(100, 1/10)
Data1000 <- MakeData(1000, 1/100)

#Compare results
BenchData <- microbenchmark(
               R10 = flowCalc(Data10$A, Data10$C),
               R100 = flowCalc(Data100$A, Data100$C),
               R1000 = flowCalc(Data1000$A, Data1000$C),
               Cpp10 = flowCalcCpp(Data10$A, Data10$C),
               Cpp100 = flowCalcCpp(Data100$A, Data100$C),
               Cpp1000 = flowCalcCpp(Data1000$A, Data1000$C))



# BenchData2 <- microbenchmark(
#                R10 = flowCalc(Data10$A, Data10$C),
#                R100 = flowCalc(Data100$A, Data100$C),
#                R1000 = flowCalc(Data1000$A, Data1000$C),
#                Cpp10 = flowCalc2(Data10$A, Data10$C),
#                Cpp100 = flowCalc2(Data100$A, Data100$C),
#                Cpp1000 = flowCalc2(Data1000$A, Data1000$C), times = 10)
```

