---
title: "Untitled"
author: "Jonathan Bourne"
date: "13/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
This code needs to be run after the SytemDynamics set up chunk

```{r}
IEEE_data_folder <- file.path(basewd, "IEEE power flow data")
Project_folder <- "/home/jonno/Dropbox/IEEE_Networks" #"/media/jonno/Seagate Expansion Drive/IEEE_Networks"
IEEE_networks <- file.path(Project_folder, "IEEE_network_files")

```


Data in common format from
http://labs.ece.uw.edu/pstca/

https://www.complexnetworks.org/s/LatexAbstractTemplate.zip

Mistakes in IEEE
Columns  7-17   Name (A) (left justify) * . This column should start at 4 not 7

```{r}


 Area_codes <-c(" 132 ", " x.x ", " 33 ", " 11 ")

data_regex <- paste0(".*(",Area_codes, ")", collapse= "|" )
data_regex <- paste0(".*(?=",Area_codes, ")", collapse= "|" ) 

data_regex <- ".*(?=HV)"

name_regex <-  paste0("(",Area_codes, ").*", collapse= "|" )

nodes <- read_delim(file = file.path(IEEE_data_folder,  IEEE_version_name ),
                    delim = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1983xx", #This pattern is never going to happen
                    skip = skip,
                    col_names = FALSE,
                    trim_ws = TRUE,
                    n_max = card_end[1]-1-skip) %>%
  mutate(
    X1 = sub("Cloverdle132", "Cloverdle 132", X1) %>% sub("Roanoke  1.0 ", "Roanoke  x.x ", .),
    Bus_Number = sub("\\s.*", "", X1) %>% as.integer(),
    Name = sub(".*? ", "", X1) %>% sub( name_regex,"", .) %>% trimws(),
    data_vect= gsub(data_regex, "", X1, perl = TRUE))



nodes_test <- read_fwf(
  file=file.path(IEEE_data_folder,  IEEE_version_name ),
  col_positions = 
    fwf_positions(start= c(1, 5,19,21,25,28,34,41,50,60,68,77,85,91,99, 107,115,124), 
                  end =  c(4,17,20,23,26,33,40,49,59,67,75,83,90,98,106,114,122,127), 
                  col_names = c("Tap bus number", "Name", "Load flow area number", "Loss zone number", "Type", "Final voltage", "Final angle", "Load MW", "Load MVAR", "Generation MW", "Generation MVAR", "Base KV", "Desired Volts", "Maximum VAR", "Minimum VAR", "Shunt conductance", "Shunt susceptance", "Remote controlled bus number")),
  skip=skip,
   n_max = card_end[1]-1-skip
  )


nodes_test2 <- read_fwf(
  file=file.path(IEEE_data_folder,  IEEE_version_name ),
  col_positions = 
    fwf_positions(start= c(1, 5,15,19,21,25,28,34,41,50,60,68,77,85,91,99, 107,115,124), 
                  end =  c(4,14,17,20,23,26,33,40,49,59,67,75,83,90,98,106,114,122,127),
                  col_names = NULL),
  skip=skip,
   n_max = card_end[1]-1-skip
  )



edges_test <- read_fwf(
  file=file.path(IEEE_data_folder,  IEEE_version_name ),
  col_positions = 
    fwf_positions(start= c(1,6,11,13,17,19,20,30,41,51,57,63,69,74,77,84,91,98, 106,113,120), 
                  end =  c(4,9,12,14,17,19,29,40,50,55,61,67,72,74,82,90,97,104,111,119,126), 
                  col_names = NULL),
  skip=skip,
   n_max = card_end[1]-1-skip
  )


```


#Create the network
```{r}

#All I need to keeo from the nodes are
#The number
#The name
#The type (optional)
# The andle
#Load
#MVar
# generation
# Generation MW

#define the area codes that are used in this network

c(14, 30, 57, 118, 300) %>% walk (~{
print(paste0("Generating IEEE Power Flow Test Case ", .x))
IEEE_number <- .x

#make file name
IEEE_version_name <- paste0("ieee", IEEE_number, "cdf.txt")

if(IEEE_number ==14){
  Area_codes <- c("HV", "LV", "ZV", "TV")
  } else if(IEEE_number ==30){
    Area_codes <- c(" 132 ", " x.x ", " 33 ", " 11 ") #doesn't work
  } else if(IEEE_number ==57){
    Area_codes <- paste0("V", 1:7)
  }else if(IEEE_number ==118){
    Area_codes <- c("V1", "V2", "V3") 
  }else { #300 the final Network
    Area_codes <- 300 #this isn't used.
  }

#Make the Area codes into the  correct regex expressions
name_regex <-  paste0("(",Area_codes, ").*", collapse= "|" )
#name_regex <- paste0("(",Area_codes, ")", collapse= "" ) %>%
 # paste0("[",., "].*") #create the regex to split out the names

data_regex <- paste0(".*(?=",Area_codes, ")", collapse= "|" ) #create the regex to split out the remaining data. Uses a positive look ahead. this means the sub function must be perl = TRUE

#each file is broken up into cards which represent different parts of the network
#The first two cards are nodes and edges respectively. At the end of each of the main cards the number -999 is shown.
#The final -999 is the end of the file followby by a single text line.
card_end <- read_delim(file = file.path(IEEE_data_folder, IEEE_version_name),
                       delim = " ",
                       col_names = FALSE) %>% 
  pull(1) %>% 
  {. =="-999"} %>% 
  which

skip <- 2


if(IEEE_number==300){

nodes <- read_delim(file = file.path(IEEE_data_folder,  IEEE_version_name ),
                    delim = " ", #This pattern is never going to happen
                    skip = 3,
                    col_names = FALSE,
                    trim_ws = TRUE,
                    n_max = card_end[1]-1-3) %>%
  select(X1, X19, everything()) %>% 
  set_names( c("Bus_Number", "Name","drop", "Loss_zone", "Type" , "final_voltage_pu", "final_angle_degs", "Load_MW", "LOAD_MVAR", "Generation_MW", "Generation_MVAR", "Base_KV", "Desired_volts_pu", "Max_MVAR", "Min_MVAR", "Conductance", "Susceptance", "Remote_controlled_Bus_number", "xx" )) %>%
  select(Bus_Number, Name, final_angle_degs:Generation_MVAR) 
} else {
  
nodes <- read_delim(file = file.path(IEEE_data_folder,  IEEE_version_name ),
                    delim = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx1983xx", #This pattern is never going to happen
                    skip = skip,
                    col_names = FALSE,
                    trim_ws = TRUE,
                    n_max = card_end[1]-1-skip) %>%
  mutate(
    X1 = sub("Cloverdle132", "Cloverdle 132", X1) %>% sub("Roanoke  1.0 ", "Roanoke  x.x ", .), #Thisi is here becuase 30 is a bit messy
    Bus_Number = sub("\\s.*", "", X1) %>% as.integer(),
    Name = sub(".*? ", "", X1) %>% sub( name_regex,"", .) %>% trimws(),
    data_vect= gsub(data_regex, "", X1, perl = TRUE)) %>%
  separate(., data_vect, into = c("drop", "Loss_zone", "Type" , "final_voltage_pu", "final_angle_degs", "Load_MW", "LOAD_MVAR", "Generation_MW", "Generation_MVAR", "Base_KV", "Desired_volts_pu", "Max_MVAR", "Min_MVAR", "Conductance", "Susceptance", "Remote_controlled_Bus_number", NA ),
           sep = "\\s+",
           convert = TRUE) %>%
 select(Bus_Number, Name, final_angle_degs:Generation_MVAR)
  
}

c("drop", "Loss_zone", "Type" , "final_voltage_pu", "final_angle_degs", "Load_MW", "LOAD_MVAR", "Generation_MW", "Generation_MVAR", "Base_KV", "Desired_volts_pu", "Max_MVAR", "Min_MVAR", "Conductance", "Susceptance", "Remote_controlled_Bus_number", NA )

c("Load_flow_area", NA, NA , "Type", "final_angle_degs", )

#ensure unique names on the nodes
nodes <- nodes %>%  #remove initial column
  group_by(Name) %>%
  mutate(counts = n()) %>% #get counts of node names
  ungroup %>%
  mutate(Name = ifelse(counts==1, Name, paste(Name,1:n(), sep = "_" ))) %>% #any nodes names that appear more than once are suffix with a unique number
  ungroup %>% select(-counts)

skip <- card_end[1]+1
edges <- read_delim(file = file.path(IEEE_data_folder, IEEE_version_name),
                   delim = " ",
                   skip = skip,
                   col_names = FALSE,
                   trim_ws = TRUE,
                   n_max = card_end[2]-1-skip) %>%
  set_names(c("Tap_bus_number", "Z_bus_number", "Load_flow_area", "Loss_zone", "Circuit", "Type", "Branch_resistance_R_pr_unit", "Branch_resistance_X_pr_unit", "Line_charging_B_pr_unit", "Line_MVA rating_No_1", "Line_MVA_rating_No_2", "Line_MVA_rating_No_3", "Control_bus_number", "Side", "Transformer_final_turns_ratio", "Transformer_final_angle", "Minimum_tap_phase_shift", "Maximum_tap_phase_shift", "Step_size", "Minimum_voltage", "Maximum_voltage"))


#The edges with near zero variance are unused anyway so I can drop them without issues
edges2 <- edges %>%
  mutate(Y = 1/Branch_resistance_X_pr_unit) %>%#We are using the DC assumuptions and the value of R is small compared to X thus we can say susceptance B = 1/X
  rename(from = Tap_bus_number, to = Z_bus_number) %>%
  select(-nearZeroVar(.),-Branch_resistance_R_pr_unit,-Branch_resistance_X_pr_unit) %>%
  left_join(select(nodes, from = Bus_Number, Name), by = "from") %>%
  left_join(select(nodes, to = Bus_Number, Name), by = "to") %>%
  mutate(Link = paste(Name.x, Name.y, sep = "-")) %>%
  select(-Name.x,-Name.y) %>%
  group_by(from, to) %>%
  #Remove parallel lines summing the susceptances
  summarise(Y = sum(Y),
            Link = first(Link)) 
  

  nodes2 <-nodes %>% select(-nearZeroVar(.)) %>%
      #A substantial amount of the generation is negative aka load, I move it into the load column
    mutate(
      Load_MW = if_else( Generation_MW<0,Load_MW-Generation_MW, Load_MW),
      Generation_MW = if_else(Generation_MW<0, 0, Generation_MW),
      Net_Generation = Generation_MW - Load_MW)


IEEE_netowork <- graph_from_data_frame(edges2, vertices = nodes2, directed = FALSE)

#The forces need balancing
IEEE_netowork <-  BalencedGenDem(IEEE_netowork, 
                   Demand = "Load_MW",
                   Generation = "Generation_MW",
                   OutputVar = "Net_Generation")

SlackRef <- SlackRefFunc(IEEE_netowork, name = "name", Generation = "Generation_MW")

IEEE_netowork <- PowerFlow(IEEE_netowork, SlackRef$name, EdgeName ="Link", VertexName = "name", Net_generation = "Net_Generation")

saveRDS(IEEE_netowork, file = file.path(IEEE_networks, paste0("IEEE_", IEEE_number, "_igraph.rds")))
   }) 

```


#Plot 118

```{r}
test2 <- as_data_frame(IEEE_118) %>%
  mutate(absPF = abs(PowerFlow),
         rank = rank(absPF))


NodePosition <- test2 %>%
  select(from, to, Link, PowerFlow) %>%
  gather(key = type, value = Node, -Link, -PowerFlow)

 set.seed(158)
  BaseCoords <- layout_with_fr(IEEE_118) %>% 
    as_tibble %>% 
    mutate(Node = names(V(IEEE_118))) %>%
    rename(Longitude = V1,
           Latitude = V2) %>%
    left_join(NodePosition, .) %>%
    left_join(nodes2 %>% 
                select(Node = Bus_Number, Name, Net_Generation) %>% 
                mutate(Node = as.character(Node),
                       Node_type = case_when(Net_Generation ==0 ~"Transmission",
                                        Net_Generation > 0 ~"Generation",
                                        TRUE ~"Demand")), .)

  BaseCoords %>%
  ggplot(aes(x = Longitude, y = Latitude, group = Link)) + geom_line() +  
    geom_point(aes(shape = Node_type, colour = Node_type))
  
    BaseCoords %>%
  ggplot(aes(x = Longitude, y = Latitude, group = Link, colour = abs(PowerFlow))) + geom_line() +  
    geom_point(aes(shape = Node_type), size = 2) +
    scale_color_viridis_c()

```
