---
title: "Untitled"
author: "Jonathan Bourne"
date: "13/09/2019"
output: html_document
editor_options: 
  chunk_output_type: console
---
This code needs to be run after the SytemDynamics set up chunk

```{r}
IEEE_data_folder <- file.path(basewd, "IEEE power flow data")
Project_folder <- "/home/jonno/Dropbox/IEEE_Networks" #/media/jonno/Seagate Expansion Drive/IEEE_Networks"
IEEE_networks <- file.path(Project_folder, "IEEE_network_files")

```


Data in common format from
http://labs.ece.uw.edu/pstca/
https://egriddata.org/dataset/ieee-30-bus-power-flow-test-case


A useful paper for cyber physical references and stufff to do with power grids. Electrical Engineer friendly
-Cyber-Physical Models for Power Grid Security Analysis: 8-Substation Case 

#Matpower version

explanation of the matpower case format can be found here
https://matpower.org/docs/ref/matpower5.0/caseformat.html

```{r}

the_ieee_test_cases <- list.files("/home/jonno/pglib-opf-master", pattern = "ieee.m", full.names = TRUE)

the_ieee_test_cases



c(14, 30, 57, 118, 300) %>% walk(~{
  
  
  mat_dat <- matpower_loader(the_ieee_test_cases[which.max(grepl(.x, the_ieee_test_cases))], output_graph = F)
  
  bus_data <- mat_dat$bus %>%
    select(bus = bus_i, demand = Pd, generation = Pmax) %>%
    mutate(net_generation = generation - demand,
           Name = bus)
  
  branch_data <- mat_dat$branch %>% #mutate(b1 = 1/x)
    select(fbus, tbus, Y = x ) %>%
    mutate(Y = 1/Y, #simplification for DC power flow assumptions
           edge_name = paste(fbus, tbus, sep = "-")) %>% #name the links
    group_by(fbus, tbus, edge_name) %>%
    #Remove parallel lines summing the susceptances
    summarise(
      Y = sum(Y)) %>% ungroup
  
  
  g<- graph_from_data_frame(branch_data, directed = F, vertices = bus_data)
  
  g <-  BalencedGenDem(g, 
                       Demand = "demand",
                       Generation = "generation",
                       OutputVar = "net_generation")
  
  SlackRef <- SlackRefFunc(g, name = "name", Generation = "generation")
  
  g <- PowerFlow(g, SlackRef = SlackRef$name, EdgeName ="edge_name", VertexName = "name", Net_generation = "net_generation", power_flow = "power_flow")
  
  saveRDS(g, file = file.path(power_grid_graphs_path , paste0("IEEE_", .x, "_igraph.rds")))
  
})

```



#Plot 118

```{r}

 {
   IEEE_number <- 118

g <- read_rds(file.path(power_grid_graphs_path , paste0("IEEE_", IEEE_number, "_igraph.rds"))) %>%
  PowerFlow(., SlackRef = "1", EdgeName ="edge_name", VertexName = "name", Net_generation = "net_generation", power_flow = "power_flow")

test2 <- as_data_frame(g) %>%
  mutate(absPF = abs(power_flow),
         rank = rank(absPF))

NodePosition <- test2 %>%
  select(from, to, edge_name, power_flow) %>%
  gather(key = type, value = node, -edge_name, - power_flow)

 set.seed(158)
  BaseCoords <- layout_with_fr(g) %>% 
    as_tibble %>% 
    mutate(node = names(V(g))) %>%
    rename(Longitude = V1,
           Latitude = V2) %>%
    left_join(NodePosition, .) %>%
    left_join(as_data_frame(g, what = "vertices") %>% 
                select(node = name, Name, net_generation) %>% 
                mutate(node = as.character(node),
                       node_type = case_when(net_generation ==0 ~"Transmission",
                                        net_generation > 0 ~"Generation",
                                        TRUE ~"Demand")), .)

  BaseCoords %>%
  ggplot(aes(x = Longitude, y = Latitude, group = edge_name)) + geom_line() +  
    geom_point(aes(shape = node_type, colour = node_type))
  
    BaseCoords %>%
  ggplot(aes(x = Longitude, y = Latitude, group = edge_name, colour = abs(power_flow))) + geom_line() +  
    geom_point(aes(shape = node_type), size = 2) +
    scale_color_viridis_c()}



```



```{r}

   IEEE_number <- 118

g <- read_rds(file.path(power_grid_graphs_path , paste0("IEEE_", IEEE_number, "_igraph.rds"))) %>%
  PowerFlow(., SlackRef = "1", EdgeName ="edge_name", VertexName = "name", Net_generation = "net_generation", power_flow = "power_flow")

g2 <- g %>% Proportional_Load(., 2, PowerFlow = "power_flow", "Link.Limit" = "edge_capacity") 
g3 <- g2 %>%
  redistribute_excess(., 
                      largest = 0.5, 
                      smallest = 0.5, 
                      fraction = 1.0, 
                      flow = power_flow, 
                      edge_capacity = edge_capacity,
                      robin_hood_mode = TRUE,
                      output_graph = TRUE)


test <- tibble(g2_capacity = get.edge.attribute(g2, "edge_capacity"), 
               g3_capacity = get.edge.attribute(g3, "edge_capacity"),
               diff = g2_capacity-g3_capacity,
               edge_centrality = edge_betweenness(g2))


test %>%
  ggplot(aes(x = g2_capacity, y = g3_capacity)) + geom_point()


test %>%
  ggplot(aes(x = g2_capacity, y = edge_centrality)) + geom_point()

c(1.005, 1.025, 1.05, 1.1, 1.2, 1.5, 2, 3, 5, 7, 10, 20)
vect_test <- expand.grid(largest = seq(0.0, 0.5, 0.1), smallest = seq(0.0, 0.5, 0.1), fraction = c(1, 0.5, 0.75, 0.25),
                         carrying_capacity = c(1.005, 1.025, 1.05, 1.1, 1.2, 1.5, 2, 3, 5, 7, 10, 20) , robin_hood_mode = c(TRUE, FALSE)) %>%
  as_tibble()

robin_hood_2 <- 1:nrow(vect_test) %>% map_df( ~{
  
  vars <-vect_test %>%
    slice(.x)
  
  g %>% Proportional_Load(., vars$carrying_capacity, PowerFlow = "power_flow", "Link.Limit" = "edge_capacity") %>%
  redistribute_excess(., 
                      largest = vars$largest, 
                      smallest = vars$smallest, 
                      fraction = vars$fraction, 
                      flow = power_flow, 
                      edge_capacity = edge_capacity,
                      robin_hood_mode = vars$robin_hood_mode,
                      output_graph = FALSE)
  
})


robin_hood_2

robin_hood_2 %>%
  filter(alpha_1 == 2) %>%
  ggplot(aes(x = largest, y = smallest, fill = load_2)) +
  geom_raster() +
  scale_fill_viridis_c() +
  facet_wrap(~fract + robin_hood_mode)



graph_path <- "power_grid_graphs/IEEE_118_igraph.rds"

parameter_df_2 <- expand.grid(largest = seq(0.0, 0.5, 0.1), smallest = seq(0.0, 0.5, 0.1), fraction = c(1, 0.5, 0.75, 0.25),
                              carrying_capacity = c(1.005, 1.025, 1.05, 1.1, 1.2, 1.5, 2, 3, 5, 7, 10, 20) , robin_hood_mode = c(TRUE, FALSE),
                              simulation_id = 1:100) %>%
  as_tibble() %>%
  mutate(
    deletion_seed = 1:n(),
    graph = "temp", #this just allows the graph to be before the path even though it is calculated after
    graph_path = graph_path,
    parameter_summary = paste0("fract_", fraction, 
             "_ec_", carrying_capacity, 
             "_largest_", largest, 
             "_smallest_", smallest, 
             "_robin_hood_", robin_hood_mode),
    graph = basename(graph_path) %>% gsub(".rds", "", .), #real graph name added in
    collapse_base = file.path( #The output collapse paths are identiacal apart from the root.
      graph, parameter_summary, 
      paste0("simulation_id_", simulation_id, ".rds" )),
       embeddings_path = file.path("embeddings", graph, paste0(parameter_summary, ".rds")
    )
  ) %>%
  group_by(carrying_capacity, simulation_id) %>%
  mutate(compute_group = 1:n()) %>%
  ungroup %>%
  group_by(simulation_id) %>%
    mutate(compute_group_strain = 1:n()) %>% #The strain groups is different to the attach groups as all 100 simulations have the same strain
    ungroup

  
write_rds(parameter_df_2, "/home/jonno/Dropbox/IEEE_Networks/analysis_parameter_files_concentrator/IEEE_118_igraph.rds")

task_id <- 40
load_file <- "IEEE_118_igraph.rds"
```

