---
title: "Untitled"
author: "Jonathan Bourne"
date: "12 December 2018"
output: html_document
editor_options: 
  chunk_output_type: console
---

http://api.gbif.org/v1/e3ce628e-9683-4af7-b7a9-47eef785d3bb


#Deletion similarity

##Round Deleted

Get the round number that an edge was deleted.

```{r}

FolderVect <- list.files(path = Saved_Sims) #folder where all the alpha FOLDERS are
FileVect <- list.files(path = Deletion_Order_Folder) %>% gsub(".rds", "",.) #folder where all the deletion order FILES are
new.type <- FolderVect[!(FolderVect %in% FileVect)] #The FOLDERS that are not present as FILES

if(length(new.type)>0){
file.path(Saved_Sims, new.type) %>%
  walk( ~{
    print(.x) #print name of folder where deletion order will be calculated
    
  Removeddf <- list.files(path = .x, full.names = TRUE) %>% #list the different network of network rds files present
    map_df(~{
        file <- .x
        print(file)
        read_rds(file) %>%
          RoundTypeRemoved (.)  %>%
          mutate(Sim = gsub(".rds", "",file) %>% basename)
      }
    ) %>%
    group_by(Sim) %>%
    mutate(RoundRemoved = ifelse(is.na(RoundRemoved), max(RoundRemoved), RoundRemoved),
         alpha = basename(.x)) %>% 
    ungroup

  Removeddf %>%
        write_rds(x = ., paste0(file.path(Deletion_Order_Folder,basename(.x)), ".rds"))
  }
  )

} 
  
AllRemovedNodes <- list.files(Deletion_Order_Folder, full.names = TRUE) %>%
  map_df(~read_rds(.x))


CleanNames <- function(df, TargetColumn, AlphaOrder){
temp <- df  %>%
  mutate_(temp1 = TargetColumn) %>%
 mutate(temp2 = temp1,
          temp2 = temp1 %>%
           str_replace_all(., "_", " ") %>%
           str_extract_all(., "([0-9])+")%>% as.numeric(.)/100,
temp3 = temp1 %>%
  str_replace_all(., "_", " ") %>%
  str_extract_all(., "([aA-zZ\\s])+", T) %>%
  paste0(., ifelse(is.na(temp2), "", temp2)),
        temp3 = temp3 %>% as.factor() %>%
  fct_relevel(., AlphaOrder)
) %>%
  select(temp3)
temp <-temp  %>% set_names(paste0(TargetColumn,"2")) 
 
temp <- bind_cols(df, temp)
return(temp)
}

```


```{r}

RoundRemovedMatrix <- AllRemovedNodes %>%
  filter(alpha == "Real_Limits", type == "Node") %>%
  mutate(RoundRemoved = ifelse(RemovalType=="Islanded", RoundRemoved, NA)) %>%
  select(Name, RoundRemoved, Sim) %>%
  spread(key = Name, value = RoundRemoved)

#test2 <- cor(test[,-1], use = "pairwise.complete.obs")

diag(test2) <- NA




PercOfTotal <- function(x,y){
  
  totalMatches <- which(x==y) %>% length()
  
  totalfails <- (!(is.na(x) & is.na(y))) %>% sum(.)
  
  totalMatches/totalfails
  
}


PercOfTotal(RoundRemovedMatrix$ABBA10, RoundRemovedMatrix$AMUL1H)

PerMat <- matrix(NA, nrow = 958, ncol = 958)
colnames(PerMat) <- names(RoundRemovedMatrix)[-1]
rownames(PerMat) <- names(RoundRemovedMatrix)[-1]

for(i in 1:958){
  
  for (n in 1:958) {
    
PerMat[n,i]    <-PercOfTotal(RoundRemovedMatrix[,i], RoundRemovedMatrix[,n])
    
  }
  
}



hftest <- as.dist(abs(PerMat-1))  %>% hclust(.)

NodeOrder <- tibble(Names = hftest$labels[hftest$order], order = 1:958)

PerMat2 <- as.tibble(PerMat) %>%
  mutate(Node1 = rownames(PerMat)) %>%
  gather(key = "Node2", value = "value",-Node1) %>%
  left_join(NodeOrder, by = c("Node1"="Names")) %>%
  left_join(NodeOrder, by = c("Node2"="Names"))

testplot <- PerMat2 %>%
  ggplot(aes(x = order.x, y = order.y, fill = value)) + geom_raster()+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

testplot

PerMat2 %>%
  filter(value != 0, Node1 != Node2) %>%
  ggplot(aes(x = value)) + geom_histogram()

PerMat3 <- PerMat2 %>%
  filter( Node1 != Node2) 

PerMat2 %>%
  filter( Node1 != Node2) %>%
  group_by(value) %>%
  summarise(count = n())


#How many clusters per cut height

Clusters <- seq(0,1, 0.005) %>%
  map_dbl(~cutree(hftest, h = .x) %>% max) %>%
  tibble(Clusters = .) %>%
  mutate(CutHeight = seq(0,1, 0.005))


Clusters <- seq(0,1, 0.01) %>%
  map_df(~cutree(hftest, h = .x) %>%
  tibble(Clusters = .) %>%
  group_by(Clusters) %>%
  summarise(counts = n()) %>%
  summarise(Clusters = max(Clusters),
            mean = mean(counts),
            max = max(counts),
            min= min(counts),
            geq5 = sum(counts>=5),
            geq10 = sum(counts>=10)) %>%
    mutate(CutHeight = .x)
  
  )


Clusters %>%
  filter(mean < 250, CutHeight > 0.95) %>%
  ggplot(aes(x = CutHeight, y = geq5)) + geom_point()



ClustGroups <- seq(0.95,1, 0.01) %>% map(~{
cutree(hftest, h = .x) %>% data_frame(datacol = ., Node = names(.)) %>%
  setNames(c(paste0("clusters_", .x*100), "Node"))
}) %>%  reduce(left_join, by = "Node") %>%
  select(Node, everything())


NlargestClusters <- ClustGroups %>%
  group_by(clusters_99) %>%
  summarise(count = n()) %>%
  filter(count>20)
  top_n(n = 11, wt = count)

ProdClustRel <- expand.grid(ClustGroups$Node, ClustGroups$Node) %>% as_tibble() %>%
  left_join(., select(ClustGroups, Node, clusters_99), by = c("Var1"="Node")) %>%
  left_join(., select(ClustGroups, Node, clusters_99), by = c("Var2"="Node")) %>%
         mutate(Cluster = ifelse(clusters_99.x == clusters_99.y, clusters_99.x, NA),
                Cluster = ifelse(!(clusters_99.x %in% NlargestClusters$clusters_99) & !is.na(Cluster),"small", Cluster),
         Var1 =  factor(Var1, levels = hftest$labels[hftest$order]),
         Var2 = factor(Var2, levels = hftest$labels[hftest$order]),
         Cluster = factor(Cluster, levels= unique(Cluster))) 

ProdClustRel %>%
  ggplot() + 
  geom_raster(aes(x = Var1, y = Var2, fill = Cluster))+
  theme(axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) +
  labs(x = "Groups", y = "Groups", title = "Failure groups") 


FailureGroups <- ClustGroups %>%
  mutate(Cluster = ifelse(clusters_99 %in% NlargestClusters$count, clusters_99, "small"),
         Cluster = factor(Cluster, levels= unique(Cluster)))


#merge with the test2 df from the proportional loading script chunk GGplotmap
##Note several chunks previous to that one need to be run

test2 %>%
  left_join(select(FailureGroups, Node, Cluster)) %>%
  filter(PositionType == "Geo Space", Cluster !="small") %>%
  mutate(Voltage = factor(Voltage),
         PositionType = factor(PositionType),
         PositionType = fct_relevel(PositionType, "Geo Space", after = 0)) %>%
  ggplot(aes(x = V1, y = V2)) + 
  geom_point(aes(colour = Cluster)) +
    geom_line(aes(colour = Voltage, group = Link))
 # facet_wrap(~Cluster, scales = "free") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank())

```

#Create loads of topo
```{r}

set.seed(169)
DeleteOrders <- MultiAttackOrder(gbase, 1000) 

  setwd(PLwd)

folder <- "TopologicalRounds"

  if(!file.exists(folder)){
    dir.create(folder)
  }
library(foreach)
library(doMC)
registerDoMC(4)
  SaveMultiAttackRounds(g, DeleteOrders, folder, TotalAttackRounds = AttackRounds, CascadeMode = F)
  
test <- list.files(folder) %>% read_csv()
```




```{r}
library(foreach)
library(doMC)
library(dplyr)
library(stringr)
registerDoMC(4)

#Generate seeds

folder <- "DeleteMe"

  if(!file.exists(folder)){
    dir.create(folder)
  }

set.seed(12)
RandNum <- data.frame(ID = 1:100, Random = sample(1:1000, 100))

for (i in 1:nrow(RandNum)) {
  
  
  CurrentSims <- list.files(folder) %>%
  str_replace_all(., "\\D", "" )
  
  NeededSims <- RandNum$ID %>%
  str_replace_all(., pattern ="\\D", "" ) %>%
  as.numeric()
  
  #The simulations still required in current run
  NeededSims2 <- NeededSims[!(NeededSims %in% CurrentSims)]
  
  #minimum ID numnber of remaining sims
  NextSim <- min(NeededSims2)
  
if (NextSim==Inf) break #Stops function making error on last iteration
  
  RandNum %>%
    filter(ID == NextSim) %>%
  saveRDS(., file.path(folder, paste0("X", NextSim, ".rds")))
  
  print(i)
}

```

```{r}

registerDoMC(4)
foreach (i = 1:nrow(RandNum)) %dopar% {
  
  
  CurrentSims <- list.files(folder) %>%
  str_replace_all(., "\\D", "" )
  
  NeededSims <- RandNum$ID %>%
  str_replace_all(., pattern ="\\D", "" ) %>%
  as.numeric()
  
  #The simulations still required in current run
  NeededSims2 <- NeededSims[!(NeededSims %in% CurrentSims)]
  
  #minimum ID numnber of remaining sims
  NextSim <- min(NeededSims2)
  
if (NextSim==Inf) break #Stops function making error on last iteration
  
  RandNum %>%
    filter(ID == NextSim) %>%
  saveRDS(., file.path(folder, paste0("X", NextSim, ".rds")))
  
  print(i)
}
```

#Animation
```{r}

RoundRemovedReal <- AllRemovedNodes %>%
  filter(alpha == "Real_Limits", type == "Edge", Sim == "Simulation_ID_1") %>%
  select(Name:RemovalType)



#test comes from the ggGeoPlot chunk in prop loading
test3 <-test2 %>%
  left_join(RoundRemovedReal, by = c("Link" = "Name"))


test4 <- 0:(max(RoundRemovedReal$RoundRemoved)-1) %>%
  map_df(~{
    
    test3 %>%
      filter(RoundRemoved>.x) %>%
      mutate(PresentInRound = .x+1)
    
  })

p <- test4 %>%
  mutate(Voltage = factor(Voltage),
         PositionType = factor(PositionType),
         PositionType = fct_relevel(PositionType, "Geo Space", after = 0),
         PresentInRound = factor(PresentInRound)) %>%
  ggplot(aes(x = V1, y = V2)) + 
  geom_line(aes(colour = Voltage, group = Link)) +
  facet_grid(~PositionType, scales = "free") +
  theme(axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank()) + 
  transition_manual(PresentInRound)

anim_save(file = file.path(basewd, "CollapseOfGrid1.gif"))

```


#Plot Islanded by round
```{r}

AlphaOrder <- c("alpha value 1.05","alpha value 1.1","alpha value 1.2","alpha value 1.5","alpha value 2" ,"alpha value 3","alpha value 5", "Topological", "Real Limits" ,"Linear Model Limits")  

test <- AllRemovedNodes %>%
  filter(type == "Node")%>%
  group_by(RoundRemoved, type, Sim, alpha, RemovalType) %>%
  summarise(count = n())

TypeCollapseDF <- test %>%
  ungroup %>%
  CleanNames(., "alpha", AlphaOrder) %>%
  filter(type == "Node") %>%
  group_by(type, alpha, RemovalType) %>%
  mutate(cumsum = cumsum(count)) %>%
  group_by(RoundRemoved, type, alpha, RemovalType, alpha2) %>%
  summarise(mean = mean(cumsum),
            sd = sd(cumsum)) %>%
  group_by(type, alpha, RemovalType, alpha2) %>%
  #mutate(cumsum = cumsum(mean)) %>%
  ungroup %>%
  mutate(PercNum = RoundRemoved/max(RoundRemoved),
         alpha = str_extract(alpha, '\\(?[0-9,.]+') %>% as.numeric(.)/100) %>%
  filter(RemovalType!="Targeted")


test2 <- test %>%
filter(alpha == "Real_Limits")  %>%
  group_by(Sim, RemovalType) %>%
  summarise(sum = sum(count))
  
  group_by(RoundRemoved, type, alpha, RemovalType) %>%
  summarise(mean = mean(count),
            sd = sd(count)) 
  


TypeCollapseDF  %>% #need to remove infinte values 
  filter(grepl("alpha", alpha2)) %>%
#  filter(grepl("105", alpha)) %>%
  ggplot(aes(x = PercNum, y =  cumsum, group = alpha2)) + 
  geom_line(aes(colour = as.numeric(alpha)), show.legend = TRUE) +  
  AlphaGrad +
  geom_line(data = filter(TypeCollapseDF,grepl("Real Limits", alpha2)), aes(fill = 'Real'), color = 'black', linetype ="longdash") +
  geom_line(data = filter(TypeCollapseDF,grepl("Linear", alpha2)), aes(fill = 'Modelled'), color = 'blue', linetype ="longdash") +
  geom_line(data = filter(TypeCollapseDF,grepl("Topo", alpha2)), aes(fill = 'Topological'), color = 'grey50', linetype ="longdash") +
  scale_fill_manual("Line Limit", values=c(1, 1, 1),
        guide=guide_legend(override.aes = list(colour=NameOrder$Colour))) +
  facet_grid(~RemovalType) +
  scale_x_continuous(labels=scales::percent) + 
  coord_cartesian(x = c(0,0.5)) +
  labs(title = "Nodes Lost by type" , 
       x = "Percent of elements attacked", 
       y = "Nodes lost by type")

```



#Make a really large number of random attacks

```{r}

```

