---
title: "Untitled"
author: "Jonathan Bourne"
date: "15 March 2019"
output: html_document
editor_options: 
  chunk_output_type: console
---


Why does the amount of power in the system rise sometimes?


```{r}
#Why is the power increasing sometimes?
test <- AttackRoundData %>%
  group_by(simulationID) %>%
  mutate(change = PowerGen-lag(PowerGen)) %>%
  ungroup

table(test$change>0)/nrow(test)

#Which nodes cause an increase in power

IncreasePower <- test %>%
  filter(change>0) %>%
  rename(RoundRemoved = NodesAttacked, Sim = simulationID) %>%
  mutate(Sim = as.character(Sim)) %>%
  left_join(testrank %>% 
              filter(type =="Node", RemovalType =="Targeted") %>% 
              mutate(Sim = gsub("Simulation_ID_", "", Sim))
            ) %>%
  left_join(VertexMetaData2)

IncreaseSummary <-IncreasePower %>%
  group_by(Name) %>%
  summarise(counts = n(),
            mean = mean(change),
            median = median(change),
            sd = sd(change),
            max = max(change),
            min = min(change),
            NodeType = first(NodeType2))

```


```{r}

Sim5689 <- test  %>%
  filter(simulationID== 5689) 

Sim5689 %>% 
#  filter(NodesAttacked<54, NodesAttacked >48) %>%
  ggplot(aes(x = NodesAttacked, y =PowerGen)) + geom_line()

test  %>%
  filter(simulationID== 5689) %>% nrow

#load simulation 5689 round 51

Sim <- readRDS(file.path("/home/jonno/Downloads", "Simulation_ID_5689.rds"))

#The largest component splits in two and this somehow causes the power to increase
Round50 <- Sim[[51]][[2]]
Round51 <- Sim[[52]][[2]]

#component 9 splits
components(Round50)$membership %>% table
components(Round51)$membership %>% table


Round50df <- Round50 %>% as_data_frame(., what = "vertices") %>% select(-Voltage,-Bus.Order) %>% 
  mutate(component = components(Round50)$membership)
Round51df <- Round51 %>% as_data_frame(., what = "vertices") %>% select(-Voltage,-Bus.Order) %>% 
  mutate(component = components(Round51)$membership)

Jointdf <- left_join(Round50df, Round51df, by = "name")

Jointdf %>%
  filter(BalencedPower.x!=0) %>%
  filter(BalencedPower.x==BalencedPower.y) %>%
  group_by(component.x, component.y) %>%
  summarise(counts = n())

#It is only nodes in component 9 that splits that cause the change in power.
Jointdf %>%
  filter(BalencedPower.x!=BalencedPower.y) %>%
  group_by(component.x, component.y) %>%
  summarise(counts = n())


Changed  <- Jointdf %>%
  filter(BalencedPower.x!=BalencedPower.y) %>%
  mutate(change = BalencedPower.x-BalencedPower.y)

Changed %>%
  group_by(component.y) %>%
  summarise(TotalChange = sum(change),
            Balance = sum(BalencedPower.y))

  MakeMapDF(Round51, read_csv(file.path(basewd, "point.csv")))  %>% as_tibble %>%
  left_join(Round51df, by = c("Node"= "name")) %>% 
  filter(component == 11| component == 12 ) %>%
    ggplot(aes(x = Latitude, y = Longitude)) + 
  geom_line(aes(group = Link), size = 0.8, arrow = arrow(angle = 15, length= unit(0.3, "cm"), type = "closed")) + 
  geom_point( #only show the nodes that have changed
             aes(colour =as.factor(component)), size = 2) +
   facet_grid(~PositionType) +
   # scale_color_brewer(type = "qual")
#  scale_color_brewer(palette = "Set1") +
  labs(title = "Failure groups")

```



```{r}
test <- as_data_frame(g) %>% mutate(alpha = abs(PowerFlow)/Link.Limit) %>% select(Link, alpha)

MakeMapDF(g, read_csv(file.path(basewd, "point.csv")))  %>%
  left_join(test) %>%
  left_join(VertexMetaData2 %>% rename(Node = Name)) %>%
    ggplot(aes(x = Latitude, y = Longitude)) + 
  geom_line(aes(group = Link, color = alpha), size = 1.5) + 
  # geom_point(#data = . %>% filter(Community != "small", Community != "medium"), #Keep only large clusters
  #            aes(shape = NodeType), size = 2) +
   facet_grid(~PositionType) +
   # scale_color_brewer(type = "qual")
  scale_color_viridis_c()
  labs(title = "Failure groups")
```

